void gst_plugin_adder_register(void) {}
void gst_plugin_app_register(void) {}
void gst_plugin_audioconvert_register(void) {}
void gst_plugin_audiorate_register(void) {}
void gst_plugin_audioresample_register(void) {}
void gst_plugin_audiotestsrc_register(void) {}
void gst_plugin_autodetect_register(void) {}
void gst_plugin_coreelements_register(void) {}
void gst_plugin_gio_register(void) {}
void gst_plugin_jpeg_register(void) {}
void gst_plugin_osxaudio_register(void) {}
void gst_plugin_playback_register(void) {}
void gst_plugin_typefindfunctions_register(void) {}
void gst_plugin_videoconvert_register(void) {}
void gst_plugin_videofilter_register(void) {}
void gst_plugin_videorate_register(void) {}
void gst_plugin_videoscale_register(void) {}
void gst_plugin_videotestsrc_register(void) {}
void gst_plugin_volume_register(void) {}
